web_sites:
  TRI:
    url: https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years-1987-2018
    queries:
      TRI_year_reported: 'option'
      TRI_zip: 'value'
  RCRAInfo:
    url: https://rcrapublic.epa.gov/rcra-public-export
    queries:
      Table_of_tables: "//table[@id='tables']"
  FRS:
    url: https://www3.epa.gov/enviro/html/fii/downloads/state_files/national_combined.zip
  GOOGLE_MAPS_COORDINATES:
    url: https://www.google.com/maps
    queries:
      address: //*[@id="searchboxinput"]
      get_button: //*[@id="searchbox-searchbutton"]
      distance_window: //*[@id="omnibox-directions"]/div/div[2]/div/button/div[1]
  GOOGLE_MAPS_DIR:
    url: https://www.google.com/maps/dir/
    queries:
      options: //*[@id="pane"]/div/div[1]/div/div/div[2]/button[2]/span[1]
      km: //*[@id="pane"]/div/div[1]/div/div/div[2]
      startig_point: //*[@id="sb_ifc50"]/input
      ending_point: //*[@id="sb_ifc51"]/input
      distance: //*[@id="section-directions-trip-0"]/div[2]/div[1]/div[1]/div[2]/div
