web_sites:
  TRI:
    url: https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years-1987-2018
    queries:
      TRI_year_reported: 'option'
      TRI_zip: 'value'
  RCRAInfo:
    url: https://rcrapublic.epa.gov/rcra-public-export
    queries:
      Table_of_tables: "//table[@id='tables']"
  FRS:
    url: https://www3.epa.gov/enviro/html/fii/downloads/state_files/national_combined.zip
  IFA:
    url: http://limitvalue.ifa.dguv.de
    queries:
      Search_bar_CAS: "//input[@id='Tbox_cas']"
      Search_bar_substance: "//input[@id='Tbox_sub']"
      Search_button: "//input[@id='Butsearch']"
      Search_button_return: "//input[@id='Button1']"
      Table_of_substance: {'id':'dgsub'}
      Table_of_limits: {'id':'DGgws'}
      Table_of_results: {'id':'DataGrid_sub'}
  OSHA:
    url: https://www.osha.gov/chemicaldata/
    queries:
      Links: {'class':'reportLink'}
      Results: {'id':'chemResultTables'}
      Properties: {'class':'table table-bordered'}
  COMPTOX:
    url: https://comptox.epa.gov/dashboard
    queries:
      chomptox_DQ: {'class':'active'}
      tables: {'class':'VueTables__table table is-bordered is-striped is-hoverable is-fullwidth'}
  NIST:
    url: https://webbook.nist.gov/
    queries:
      tables: {'class':'data'}
  # FRS:
  #   url: https://www.epa.gov/frs/frs-query
  #   queries:
  #     Facility_Identification: "//select[@id='Facility']"
  #     By_name: 'Facility Name (Enter a partial or complete Facility Name)'
  #     Name: "//input[@name='fac_value']"
  #     Radius1: "//div[@class='form-item form-type-radio form-item-radios']"
  #     By_containing1: "//label[@for='Within']"
  #     Zip: "//input[@name='postal_code']"
  #     City: "//input[@name='city_name']"
  #     County: "//input[@name='county_name']"
  #     State: "//select[@name='state_code']"
  #     Search_button: "//input[@type='submit']"
  #     Radius2: "//div[@class='form-item form-type-radio form-item-radios']"
  #     By_containing2: "label[text() = 'All National Systems or']"
  #     Close_junk_window: "//a[@class='acsInviteButton acsDeclineButton']"
  #     Radius3: "//div[@class='form-item form-type-radio form-item-radios']"
  #     By_containing3: "//label[@for='Within2']"
  #     Address: "//input[@name='location_address']"
  #     Link: "//td[@align='left']//a[@target='_blank']"
      #By_containing2: "label[text() = 'Selected National Systems from the list below:']"
      #Select_EGRID: "//label[@for='EGRID']"
      #Select_EIS: "//label[@for='EIS']"
      #Select_TRI: "//label[@for='TRIS']"
      #Select_RCRAInfo: "//label[@for='RCRAInfo']"
